# ==============================================================================
# SPRING BOOT APPLICATION CONFIGURATION
# ==============================================================================
spring.application.name=NovaApparel
server.port=8080

# 1. DATABASE CONFIGURATION (MICROSOFT SQL SERVER)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=NovaApparelDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. JPA & HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# 3. JWT SECURITY CONFIGURATION
jwt.secret=FashionManagementSystemSecretKey2026StreetwearLuxuryHighFashionBoutiqueSecretKey999
jwt.expiration=86400000

# 4. VNPAY SANDBOX CONFIGURATION
vnpay.tmnCode=DEMO_TMN_CODE
vnpay.hashSecret=DEMO_HASH_SECRET
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:5173/orders

# 5. SWAGGER / OPENAPI UI CONFIGURATION
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
